name: Production Workflow
on:
  push:
    branches: [master]
jobs:
  test:
    name: Test Website
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Node Js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies and lint
        run: |
          npm install
          npm run lint
        env:
          CI: true
  build:
    needs: [test]
    name: Build Website
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Node Js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies and build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
  deploy:
    needs: [test, build]
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/nextjs-ci-cd
            git config core.fileMode false
            git clean -f
            git reset --hard
            git pull origin master
            npm install
            npm run build
            pm2 reload 0
