name: Production Workflow
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Clone Repository
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies and build and lint
        run: |
          npm install
          npm run build --if-present
          npm run lint
        env:
          CI: true
