name: Production Workflow
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v1
      - name: Install NPM dependencies and build and lint
        run: |
          npm install
          npm run build --if-present
          npm run lint
        env:
          CI: true
