name: Production Workflow
on:
  push:
    branches: [master]
jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM dependencies and test
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm install
          npm run lint
        env:
          CI: true
  buildWebsite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Install NPM dependencies and build
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          npm install
          npm run build
        env:
          CI: true
  deployWebsite:
    needs: [lintTest, buildWebsite]
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/nextjs-ci-cd
            git config core.fileMode false
            git clean -f
            git reset --hard
            git pull origin master
            npm install
            npm run build
            pm2 reload 0
